# Generated by Django 5.2.3 on 2025-07-02 15:54

import django.db.models.deletion
import manhwas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Manhwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(blank=True, max_length=500)),
                ('en_title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('season', models.PositiveIntegerField(default=1)),
                ('day_of_week', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'thursday'), ('fri', 'Friday')], max_length=30)),
                ('cover', models.ImageField(upload_to=manhwas.models.manhwa_cover_upload_to)),
                ('publication_datetime', models.DateTimeField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1)),
                ('file', models.FileField(upload_to=manhwas.models.manhwa_file_upload_to)),
                ('downloads_count', models.PositiveIntegerField(default=0)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_modified', models.DateTimeField(auto_now=True)),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='manhwas.manhwa')),
            ],
        ),
        migrations.CreateModel(
            name='ManhwaGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manhwas', to='manhwas.genre')),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='manhwas.manhwa')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='manhwas.manhwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='manhwa',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manhwas', to='manhwas.studio'),
        ),
    ]
