# Generated by Django 5.2.3 on 2025-07-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='genres',
            field=models.ManyToManyField(related_name='manhwas', to='manhwas.genre'),
        ),
        migrations.DeleteModel(
            name='ManhwaGenre',
        ),
    ]
