# Generated by Django 5.2.3 on 2025-07-04 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0002_manhwa_genres_delete_manhwagenre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='manhwa',
            old_name='views',
            new_name='views_count',
        ),
        migrations.AlterUniqueTogether(
            name='episode',
            unique_together={('number', 'manhwa')},
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'manhwa')},
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_viewed', models.DateTimeField(auto_now_add=True)),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manhwas.manhwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('manhwa', 'user')},
            },
        ),
    ]
