# Generated by Django 5.2.3 on 2025-07-05 08:53

import django.db.models.deletion
import manhwas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0003_rename_views_manhwa_views_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد دانلود'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to=manhwas.models.manhwa_file_upload_to, verbose_name='فایل قسمت'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='manhwas.manhwa', verbose_name='مانهوا'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(default=1, verbose_name='شماره قسمت'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.CharField(max_length=500, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='cover',
            field=models.ImageField(upload_to=manhwas.models.manhwa_cover_upload_to, verbose_name='تصویر مانهوا'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='day_of_week',
            field=models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'thursday'), ('fri', 'Friday')], max_length=30, verbose_name='روز هفته'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='en_title',
            field=models.CharField(max_length=500, verbose_name='نام انگلیسی'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='fa_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='نام فارسی'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='genres',
            field=models.ManyToManyField(related_name='manhwas', to='manhwas.genre', verbose_name='ژانر'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='publication_datetime',
            field=models.DateTimeField(verbose_name='تاریخ انتشار'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='season',
            field=models.PositiveIntegerField(default=1, verbose_name='فصل'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manhwas', to='manhwas.studio', verbose_name='استودیو'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='summary',
            field=models.TextField(verbose_name='خلاصه داستان'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='manhwas.manhwa', verbose_name='مانهوا'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='title',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='view',
            name='datetime_viewed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ بازدید'),
        ),
        migrations.AlterField(
            model_name='view',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manhwas.manhwa', verbose_name='مانهوا'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Likes count')),
                ('dis_likes_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='disLikes count')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='تاریخ ویرایش')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='author')),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manhwas.manhwa', verbose_name='مانهوا')),
            ],
            options={
                'unique_together': {('manhwa', 'author', 'text')},
            },
        ),
        migrations.CreateModel(
            name='CommentReAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('lk', 'like'), ('dlk', 'dislike')], max_length=10, verbose_name='reaction')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manhwas.comment', verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'unique_together': {('user', 'comment')},
            },
        ),
    ]
