# Generated by Django 5.2.3 on 2026-08-31 21:32

import django.core.files.storage
import manhwas.services
import pathlib
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0003_chapter_is_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterimage',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='chapterimage',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/code/protected')), upload_to=manhwas.services.chapter_images_upload_to),
        ),
    ]
