# Generated by Django 5.2.3 on 2025-07-06 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0004_alter_episode_datetime_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ('number',)},
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='dis_likes_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد مخالف (دیسلایک)'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد موافق (لایک)'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manhwas.comment', verbose_name='دیدگاه ها'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('lk', 'like'), ('dlk', 'dislike')], max_length=10, verbose_name='واکنش'),
        ),
    ]
