# Generated by Django 5.2.3 on 2026-09-01 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0004_chapterimage_token_alter_chapterimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_spoiler',
            field=models.BooleanField(default=False),
        ),
    ]
