# Generated by Django 5.2.3 on 2026-09-07 18:34

import manhwas.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0005_comment_is_spoiler'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ticket',
            name='manhwas_tic_viewing_b25bf5_idx',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='viewing_status',
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('op', 'open ticket'), ('cl', 'close ticket')], default='op', max_length=20),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='cover',
            field=models.ImageField(blank=True, upload_to=manhwas.services.chapter_cover_upload_to),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status'], name='manhwas_tic_status_01e2c5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_seen'], name='manhwas_tic_status_f2a7bd_idx'),
        ),
    ]
