# Generated by Django 5.2.3 on 2025-07-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0005_alter_episode_options_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
