# Generated by Django 5.2.3 on 2025-07-07 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0007_alter_rate_user_alter_view_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='manhwas.manhwa', verbose_name='episodes'),
        ),
    ]
