# Generated by Django 5.2.3 on 2025-07-21 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0009_alter_episode_manhwa_alter_manhwa_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='manhwas.comment')),
                ('replied_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manhwas.comment')),
            ],
        ),
    ]
