# Generated by Django 5.2.3 on 2025-08-06 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0010_commentreply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('dis_likes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_comments', to=settings.AUTH_USER_MODEL)),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_comments', to='manhwas.manhwa')),
                ('parent', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manhwas.newcomment')),
            ],
        ),
    ]
