# Generated by Django 5.2.3 on 2025-08-07 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0011_newcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcomment',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='childes', to='manhwas.newcomment'),
        ),
    ]
