# Generated by Django 5.2.3 on 2025-08-08 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0012_alter_newcomment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manhwas.newcomment', verbose_name='دیدگاه ها'),
        ),
    ]
