# Generated by Django 5.2.3 on 2025-08-08 16:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0013_alter_commentreaction_comment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcomment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterUniqueTogether(
            name='newcomment',
            unique_together={('manhwa', 'author', 'text')},
        ),
    ]
