# Generated by Django 5.2.3 on 2025-08-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0014_alter_newcomment_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentreply',
            name='replied_comment',
        ),
        migrations.RemoveField(
            model_name='commentreply',
            name='main_comment',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
