# Generated by Django 5.2.3 on 2025-08-13 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0015_remove_commentreply_replied_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='last_upload',
            field=models.CharField(default='Not Uploaded', editable=False),
        ),
        migrations.AlterField(
            model_name='episode',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد دانلود'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='manhwa',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='episodes', to='manhwas.manhwa', verbose_name='قسمت ها'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='شماره قسمت'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد بازدید'),
        ),
        migrations.AlterField(
            model_name='newcomment',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manhwas.manhwa'),
        ),
    ]
