# Generated by Django 5.2.3 on 2025-08-18 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0016_manhwa_last_upload_alter_episode_downloads_count_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewComment',
            new_name='Comment',
        ),
    ]
