# Generated by Django 5.2.3 on 2025-09-18 19:46

import django.db.models.deletion
import manhwas.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0018_alter_comment_author_alter_comment_parent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='title',
            field=models.CharField(default='Ticket Title', max_length=150),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manhwas.comment', verbose_name='comment'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='reaction',
            field=models.CharField(choices=[('lk', 'like'), ('dlk', 'dislike')], max_length=10, verbose_name='reaction'),
        ),
        migrations.AlterField(
            model_name='commentreaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime created'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime modified'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='downloads_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='download count'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file',
            field=models.FileField(upload_to=manhwas.models.manhwa_file_upload_to, verbose_name='episode file'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='number',
            field=models.PositiveIntegerField(blank=True, editable=False, verbose_name='number of episode'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='cover',
            field=models.ImageField(upload_to=manhwas.models.manhwa_cover_upload_to, verbose_name='manhwa cover'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='datetime_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime created'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='datetime_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='datetime modified'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='day_of_week',
            field=models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'thursday'), ('fri', 'Friday')], max_length=30, verbose_name='day of the week'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='en_title',
            field=models.CharField(max_length=500, verbose_name='english title'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='fa_title',
            field=models.CharField(blank=True, max_length=500, verbose_name='persian title'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='genres',
            field=models.ManyToManyField(related_name='manhwas', to='manhwas.genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='publication_datetime',
            field=models.DateTimeField(verbose_name='publication datetime'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='season',
            field=models.PositiveIntegerField(default=1, verbose_name='season'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manhwas', to='manhwas.studio', verbose_name='studio'),
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='views_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='views count'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='manhwas.manhwa', verbose_name='manhwa'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='view',
            name='datetime_viewed',
            field=models.DateTimeField(auto_now_add=True, verbose_name='datetime viewed'),
        ),
        migrations.AlterField(
            model_name='view',
            name='manhwa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manhwas.manhwa', verbose_name='manhwa'),
        ),
        migrations.AlterField(
            model_name='view',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
