# Generated by Django 5.2.3 on 2025-09-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0019_remove_ticket_text_remove_ticket_type_ticket_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='viewing_status',
            field=models.CharField(choices=[('r', 'read ticket'), ('unr', 'unread ticket')], default='unr', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketmessage',
            name='message_sender',
            field=models.CharField(choices=[('user', 'From User'), ('admin', 'From Admin')], default='user', max_length=20),
        ),
    ]
