# Generated by Django 5.2.3 on 2025-10-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0021_ticketmessage_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticketmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['datetime_created', 'datetime_modified'], name='manhwas_man_datetim_0b139d_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['studio', 'day_of_week'], name='manhwas_man_studio__51739c_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['day_of_week'], name='manhwas_man_day_of__95fa28_idx'),
        ),
    ]
