# Generated by Django 5.2.3 on 2025-10-01 12:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0022_alter_ticket_options_alter_ticketmessage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['level'], name='manhwas_com_level_eea417_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['manhwa', '-created_at'], name='manhwas_com_manhwa__03e79d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='manhwas_com_author__5bfd12_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'level'], name='manhwas_com_parent__56e1f6_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['manhwa', 'number'], name='manhwas_epi_manhwa__423429_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['-downloads_count'], name='manhwas_epi_downloa_38b5fe_idx'),
        ),
        migrations.AddIndex(
            model_name='episode',
            index=models.Index(fields=['-datetime_created'], name='manhwas_epi_datetim_0553a9_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['-publication_datetime'], name='manhwas_man_publica_1bafff_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['-views_count'], name='manhwas_man_views_c_c4cd75_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['en_title'], name='manhwas_man_en_titl_f57561_idx'),
        ),
    ]
