# Generated by Django 5.2.3 on 2026-08-10 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0023_comment_manhwas_com_level_eea417_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='title_slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
