# Generated by Django 5.2.3 on 2026-08-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0024_manhwa_title_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manhwa',
            name='last_upload_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='manhwa',
            name='publication_status',
            field=models.CharField(choices=[('cp', 'Currently Publishing'), ('c', 'Concluded'), ('up', 'UnPublished')], default='up'),
        ),
        migrations.AlterUniqueTogether(
            name='manhwa',
            unique_together={('en_title', 'season')},
        ),
    ]
