# Generated by Django 5.2.3 on 2026-08-17 13:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0025_manhwa_is_hot_manhwa_last_upload_time_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching_status', models.CharField(choices=[('WR', 'Will Reading'), ('NR', 'Now Reading'), ('ST', 'Stopped'), ('FN', 'Finished')], default='WR', max_length=10)),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_listed', to='manhwas.manhwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
