# Generated by Django 5.2.3 on 2026-08-17 17:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0026_watchlist'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watching_status',
            field=models.CharField(blank=True, choices=[('WR', 'Will Reading'), ('NR', 'Now Reading'), ('ST', 'Stopped'), ('FN', 'Finished')], default='WR', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'manhwa')},
        ),
    ]
