# Generated by Django 5.2.3 on 2026-08-19 11:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0027_alter_watchlist_watching_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ('-datetime_viewed',)},
        ),
        migrations.RemoveIndex(
            model_name='manhwa',
            name='manhwas_man_datetim_0b139d_idx',
        ),
        migrations.RemoveIndex(
            model_name='manhwa',
            name='manhwas_man_views_c_c4cd75_idx',
        ),
        migrations.RemoveIndex(
            model_name='manhwa',
            name='manhwas_man_en_titl_f57561_idx',
        ),
        migrations.AlterField(
            model_name='manhwa',
            name='day_of_week',
            field=models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'ُThursday'), ('fri', 'Friday')], max_length=30, verbose_name='day of the week'),
        ),
        migrations.AddIndex(
            model_name='commentreaction',
            index=models.Index(fields=['comment', 'reaction'], name='manhwas_com_comment_4f28d6_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['publication_status'], name='manhwas_man_publica_b6a996_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['manhwa', 'rating'], name='manhwas_rat_manhwa__f30fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['user', 'rating'], name='manhwas_rat_user_id_11426a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['viewing_status'], name='manhwas_tic_viewing_b25bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'message_sender'], name='manhwas_tic_ticket__8c2cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['manhwa'], name='manhwas_vie_manhwa__68e442_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'watching_status'], name='manhwas_wat_user_id_2ab74a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['manhwa', 'watching_status'], name='manhwas_wat_manhwa__883a85_idx'),
        ),
    ]
