# Generated by Django 5.2.3 on 2026-08-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0028_alter_view_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhwa',
            name='hero_cover',
            field=models.ImageField(blank=True, null=True, upload_to='Manhwa/hero/'),
        ),
    ]
