# Generated by Django 5.2.3 on 2026-08-28 16:55

import django.db.models.deletion
import django_ckeditor_5.fields
import manhwas.services
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.CharField(max_length=500, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Manhwa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_title', models.CharField(blank=True, max_length=500, verbose_name='persian title')),
                ('en_title', models.CharField(max_length=500, verbose_name='english title')),
                ('title_slug', models.SlugField(blank=True, max_length=60, unique=True)),
                ('summary', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text')),
                ('season', models.PositiveIntegerField(default=1, verbose_name='season')),
                ('day_of_week', models.CharField(choices=[('sat', 'Saturday'), ('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'ُThursday'), ('fri', 'Friday')], max_length=30, verbose_name='day of the week')),
                ('cover', models.ImageField(upload_to=manhwas.services.manhwa_cover_upload_to, verbose_name='manhwa cover')),
                ('hero_cover', models.ImageField(blank=True, null=True, upload_to='Manhwa/hero/')),
                ('views_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='views count')),
                ('publication_datetime', models.DateTimeField(verbose_name='publication datetime')),
                ('publication_status', models.CharField(choices=[('cp', 'Currently Publishing'), ('c', 'Concluded'), ('up', 'UnPublished')], default='up')),
                ('is_hot', models.BooleanField(default=False)),
                ('last_upload_time', models.DateTimeField(blank=True, null=True)),
                ('last_upload', models.CharField(default='Not Uploaded', editable=False)),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='datetime modified')),
                ('genres', models.ManyToManyField(related_name='manhwas', to='manhwas.genre', verbose_name='genre')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='manhwas', to='manhwas.studio', verbose_name='studio')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('level', models.PositiveSmallIntegerField(default=0, editable=False)),
                ('likes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('dis_likes_count', models.PositiveIntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='manhwas.comment')),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manhwas.manhwa')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('cover', models.ImageField(blank=True, null=True, upload_to=manhwas.services.chapter_images_upload_to)),
                ('number', models.PositiveIntegerField(blank=True, editable=False, verbose_name='number of chapters')),
                ('zip_file', models.FileField(upload_to='temp_zips/', verbose_name='chapter zip file')),
                ('downloads_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='download count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='datetime created')),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chapters', to='manhwas.manhwa', verbose_name='manhwas')),
            ],
            options={
                'ordering': ('number',),
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='rating')),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='manhwas.manhwa', verbose_name='manhwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='title not set', max_length=150)),
                ('viewing_status', models.CharField(choices=[('r', 'read ticket'), ('unr', 'unread ticket')], default='unr', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sender', models.CharField(choices=[('user', 'From User'), ('admin', 'From Admin')], default='user', max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='manhwas.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_viewed', models.DateTimeField(auto_now_add=True, verbose_name='datetime viewed')),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='manhwas.manhwa', verbose_name='manhwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ('-datetime_viewed',),
            },
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watching_status', models.CharField(blank=True, choices=[('wr', 'Will Reading'), ('nr', 'Now Reading'), ('st', 'Stpped'), ('fn', 'Finished')], default='wr', max_length=10)),
                ('manhwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_listed', to='manhwas.manhwa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChapterImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=manhwas.services.chapter_images_upload_to)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='manhwas.chapter')),
            ],
            options={
                'ordering': ('order',),
                'indexes': [models.Index(fields=['chapter'], name='manhwas_cha_chapter_8fb746_idx')],
            },
        ),
        migrations.CreateModel(
            name='CommentReAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(choices=[('lk', 'like'), ('dlk', 'dislike')], max_length=10, verbose_name='reaction')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='manhwas.comment', verbose_name='comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_reactions', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'indexes': [models.Index(fields=['comment', 'reaction'], name='manhwas_com_comment_4f28d6_idx')],
                'unique_together': {('user', 'comment')},
            },
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['level'], name='manhwas_com_level_eea417_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['manhwa', '-created_at'], name='manhwas_com_manhwa__03e79d_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', '-created_at'], name='manhwas_com_author__5bfd12_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent', 'level'], name='manhwas_com_parent__56e1f6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('manhwa', 'author', 'text')},
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['manhwa', 'number'], name='manhwas_cha_manhwa__b1e391_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['-downloads_count'], name='manhwas_cha_downloa_1cd83d_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['-created_at'], name='manhwas_cha_created_d366fa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('number', 'manhwa')},
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['manhwa', 'rating'], name='manhwas_rat_manhwa__f30fb0_idx'),
        ),
        migrations.AddIndex(
            model_name='rate',
            index=models.Index(fields=['user', 'rating'], name='manhwas_rat_user_id_11426a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rate',
            unique_together={('user', 'manhwa')},
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['studio', 'day_of_week'], name='manhwas_man_studio__51739c_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['day_of_week'], name='manhwas_man_day_of__95fa28_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['-publication_datetime'], name='manhwas_man_publica_1bafff_idx'),
        ),
        migrations.AddIndex(
            model_name='manhwa',
            index=models.Index(fields=['publication_status'], name='manhwas_man_publica_b6a996_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='manhwa',
            unique_together={('en_title', 'season')},
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['viewing_status'], name='manhwas_tic_viewing_b25bf5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketmessage',
            index=models.Index(fields=['ticket', 'message_sender'], name='manhwas_tic_ticket__8c2cb8_idx'),
        ),
        migrations.AddIndex(
            model_name='view',
            index=models.Index(fields=['manhwa'], name='manhwas_vie_manhwa__68e442_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='view',
            unique_together={('manhwa', 'user')},
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'watching_status'], name='manhwas_wat_user_id_2ab74a_idx'),
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['manhwa', 'watching_status'], name='manhwas_wat_manhwa__883a85_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'manhwa')},
        ),
    ]
