# Generated by Django 5.2.3 on 2026-08-28 18:01

import manhwas.services
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=manhwas.services.chapter_cover_upload_to),
        ),
    ]
