# Generated by Django 5.2.3 on 2026-09-19 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0006_remove_ticket_manhwas_tic_viewing_b25bf5_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manhwa',
            options={'ordering': ('-datetime_created',)},
        ),
    ]
