# Generated by Django 5.2.3 on 2026-09-19 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manhwas', '0007_alter_manhwa_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('manhwa', 'number')},
        ),
        migrations.AlterModelOptions(
            name='chapterimage',
            options={'ordering': ('chapter', 'order')},
        ),
        migrations.AlterModelOptions(
            name='commentreaction',
            options={'ordering': ('comment',)},
        ),
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ('manhwa', 'rating')},
        ),
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ('user',)},
        ),
    ]
