# Generated by Django 5.2.3 on 2026-08-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_level',
            field=models.CharField(choices=[('suc', 'Success'), ('inf', 'Info'), ('war', 'Warning'), ('fal', 'Fail')], default='inf', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('epp', 'Chapter Published'), ('rac', 'Reacted Comment'), ('rpc', 'Replied Comment'), ('sys', 'System Notify')], max_length=10),
        ),
    ]
