services:
  db:
    image: postgres:14-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env

    volumes:
      - .:/code

    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/code

    depends_on:
      - db
      - redis
      - web

    env_file:
      - .env

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/code

    depends_on:
      - db
      - redis
      - web

    env_file:
      - .env

volumes:
  postgres_data:
  redis_data:
