# Generated by Django 5.2.3 on 2026-07-30 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='is_subscriber',
            new_name='is_active',
        ),
    ]
