# Generated by Django 5.2.3 on 2026-07-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_subscription_expire_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='expiration_date',
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='authority',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
