# Generated by Django 5.2.3 on 2026-08-17 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_rename_is_subscriber_subscription_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='last_validation',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
