# Generated by Django 5.2.3 on 2026-07-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_remove_subscriptionorder_expiration_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='is_allowed',
            new_name='is_purchasable',
        ),
    ]
