# Generated by Django 5.2.3 on 2026-07-29 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_is_allowed_subscriptionplan_is_purchasable'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='is_consumed',
            field=models.BooleanField(default=False),
        ),
    ]
