# Generated by Django 5.2.3 on 2026-07-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_subscriptionorder_is_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='is_expired',
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='payment_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='ref_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
