upstream django_app {
    server web:8000;
}
upstream next_app {
    server frontend:3000;
}

server {
    listen 80;
    server_name localhost; # change in production
    
    location /static/ {
        alias /code/staticfiles/;
    }
    location /media/ {
        alias /code/media/;
    }
    location /internal/ {
        internal;
        alias /code/protected/;
        
        add_header 'Access-Control-Allow-Origin' 'http://localhost:3000' always;
        add_header 'Access-Control-Allow-Credentials' 'true' always;
    }

    location ~ ^/(api|admin|ckeditor5|__debug__)/ {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # بقیه → Next.js
    location / {
        proxy_pass http://next_app;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}