from config import settings

_DEFAULTS = {
    "OTP_REDIS_KEY": "otp:{}",
    "OTP_ATTEMPT_REDIS_KEY": "otp:attempt:{}",
    "OTP_BLACKLISTED_REDIS_KEY": "otp:blacklisted:{}",
    "PASS_ATTEMPT_REDIS_KEY": "pass:attempt:{}",
    "PASS_BLACKLISTED_REDIS_KEY": "pass:blacklisted:{}",
    "OTP_DEFAULT_LENGTH" : 5,
    "OTP_TTL" : 120,
    "ATTEMPT_TTL" : 300,
    "BLACKLIST_TTL" : 180,
    "MAX_ATTEMPTS" : 3,
}

_config = getattr(settings, "OTP_SETTINGS", {})


OTP_REDIS_KEY = _config.get("OTP_REDIS_KEY", _DEFAULTS['OTP_REDIS_KEY'])
OTP_ATTEMPT_REDIS_KEY = _config.get("OTP_ATTEMPT_REDIS_KEY", _DEFAULTS['OTP_ATTEMPT_REDIS_KEY'])
OTP_BLACKLISTED_REDIS_KEY = _config.get("OTP_BLACKLISTED_REDIS_KEY", _DEFAULTS['OTP_BLACKLISTED_REDIS_KEY'])

PASS_ATTEMPT_REDIS_KEY = _config.get("PASS_ATTEMPT_REDIS_KEY", _DEFAULTS['PASS_ATTEMPT_REDIS_KEY'])
PASS_BLACKLISTED_REDIS_KEY = _config.get("PASS_BLACKLISTED_REDIS_KEY", _DEFAULTS['PASS_BLACKLISTED_REDIS_KEY'])

OTP_DEFAULT_LENGTH = _config.get("OTP_DEFAULT_LENGTH", _DEFAULTS["OTP_DEFAULT_LENGTH"])
OTP_TTL = _config.get("OTP_TTL", _DEFAULTS["OTP_TTL"])
ATTEMPT_TTL = _config.get("ATTEMPT_TTL", _DEFAULTS["ATTEMPT_TTL"])
BLACKLIST_TTL = _config.get("BLACKLIST_TTL", _DEFAULTS["BLACKLIST_TTL"])
MAX_ATTEMPTS = _config.get("MAX_ATTEMPTS", _DEFAULTS["MAX_ATTEMPTS"])