# Generated by Django 5.2.3 on 2025-07-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('manhwas', '0007_alter_rate_user_alter_view_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='watch_list',
            field=models.ManyToManyField(blank=True, to='manhwas.manhwa'),
        ),
    ]
